export interface Clip {
  id: string;
  title: string;
  hook: string;
  episode: string;
  episodeNumber: number;
  guest?: string;
  guestTitle?: string;
  date: string;
  youtubeId: string;
  startSeconds: number;
  endSeconds: number;
  viralityScore: number;
  energy: "high" | "medium" | "low";
  type: "hot_take" | "insight" | "funny" | "breaking_news" | "guest_highlight" | "education";
  platforms: string[];
  tags: string[];
  sentiment: "bullish" | "bearish" | "neutral" | "mixed";
}

// Demo content library — real Moon or Bust episodes
// Timestamps extracted via Gemini 2.5 Flash on 2026-03-08
// All startSeconds/endSeconds confirmed against source video
export const DEMO_CLIPS: Clip[] = [
  // ═══ BRETT JOHNSON — Ep 92 ═══
  {
    id: "clip-001",
    title: "FBI's Most Wanted Turned Informant",
    hook: "He built the first organized cybercrime ring on the internet — then the FBI flipped him",
    episode: "How Former FBI's Most Wanted Hacker Cashed Out In Crypto",
    episodeNumber: 92,
    guest: "Brett Johnson",
    guestTitle: "Former FBI Most Wanted, Cybersecurity Consultant",
    date: "2022-05-20",
    youtubeId: "A2iZWeH_ojo",
    startSeconds: 239,
    endSeconds: 300,
    viralityScore: 9.5,
    energy: "high",
    type: "guest_highlight",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X", "LinkedIn"],
    tags: ["cybercrime", "FBI", "security", "crypto"],
    sentiment: "neutral",
  },
  {
    id: "clip-002",
    title: "The Crypto Cashout Playbook",
    hook: "Step-by-step: how criminals actually turn stolen crypto into clean cash",
    episode: "How Former FBI's Most Wanted Hacker Cashed Out In Crypto",
    episodeNumber: 92,
    guest: "Brett Johnson",
    guestTitle: "Former FBI Most Wanted, Cybersecurity Consultant",
    date: "2022-05-20",
    youtubeId: "A2iZWeH_ojo",
    startSeconds: 525,
    endSeconds: 585,
    viralityScore: 9.2,
    energy: "high",
    type: "insight",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["hacking", "cashout", "money laundering", "crypto"],
    sentiment: "neutral",
  },

  // ═══ BILLY MARKUS — Ep 20 ═══
  {
    id: "clip-003",
    title: "DOGE Was Built in Hours",
    hook: "The creator of Dogecoin made it in a few hours — most of that time was adding Comic Sans",
    episode: "Dogecoin Co-Creator Billy Markus Interview",
    episodeNumber: 20,
    guest: "Billy Markus",
    guestTitle: "Co-creator, Dogecoin",
    date: "2021-07-25",
    youtubeId: "ehNgfJziVcg",
    startSeconds: 109,
    endSeconds: 155,
    viralityScore: 9.4,
    energy: "high",
    type: "guest_highlight",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["Dogecoin", "DOGE", "meme coins", "origin story"],
    sentiment: "neutral",
  },
  {
    id: "clip-004",
    title: "Why the DOGE Creator Sold Everything",
    hook: "Billy Markus sold all his Dogecoin in 2015 to pay rent — then watched it moon without him",
    episode: "Dogecoin Co-Creator Billy Markus Interview",
    episodeNumber: 20,
    guest: "Billy Markus",
    guestTitle: "Co-creator, Dogecoin",
    date: "2021-07-25",
    youtubeId: "ehNgfJziVcg",
    startSeconds: 140,
    endSeconds: 195,
    viralityScore: 9.1,
    energy: "medium",
    type: "hot_take",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X", "LinkedIn"],
    tags: ["Dogecoin", "regret", "origin story", "creator"],
    sentiment: "mixed",
  },

  // ═══ TIM DRAPER — Ep 18 ═══
  {
    id: "clip-005",
    title: "Tim Draper's Billion-Dollar Bitcoin Bet",
    hook: "He bought 30,000 Bitcoin from the Silk Road auction — that bet is now worth over a billion dollars",
    episode: "Tim Draper Talks DeFi",
    episodeNumber: 18,
    guest: "Tim Draper",
    guestTitle: "Venture Capitalist, Draper Associates",
    date: "2021-07-20",
    youtubeId: "2G_MBcDqLZ0",
    startSeconds: 310,
    endSeconds: 370,
    viralityScore: 9.0,
    energy: "high",
    type: "guest_highlight",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X", "LinkedIn"],
    tags: ["Bitcoin", "venture capital", "Tim Draper", "Silk Road"],
    sentiment: "bullish",
  },
  {
    id: "clip-006",
    title: "Why Would Anyone Hold Fiat?",
    hook: "Tim Draper asks the question every Bitcoiner is thinking: why hold a currency tied to politicians?",
    episode: "Tim Draper Talks DeFi",
    episodeNumber: 18,
    guest: "Tim Draper",
    guestTitle: "Venture Capitalist, Draper Associates",
    date: "2021-07-20",
    youtubeId: "2G_MBcDqLZ0",
    startSeconds: 80,
    endSeconds: 130,
    viralityScore: 8.5,
    energy: "high",
    type: "hot_take",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["Bitcoin", "fiat", "macro", "sound money"],
    sentiment: "bullish",
  },

  // ═══ MIKE DEMARAIS — Ep 56 ═══
  {
    id: "clip-007",
    title: "The $90,000 Pair of Socks",
    hook: "UniSocks turned a $12 pair of socks into $90K through bonding curves — the Yeezys of blockchain",
    episode: "Breaking Into Crypto Feat. Mike Demarais",
    episodeNumber: 56,
    guest: "Mike Demarais",
    guestTitle: "Co-founder, Rainbow Wallet",
    date: "2021-12-02",
    youtubeId: "VD5RDcFM7xM",
    startSeconds: 1910,
    endSeconds: 2010,
    viralityScore: 9.1,
    energy: "high",
    type: "funny",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["UniSocks", "DeFi", "NFT", "bonding curve"],
    sentiment: "bullish",
  },
  {
    id: "clip-008",
    title: "VCs Are Ruining Crypto",
    hook: "Rainbow Wallet's co-founder calls out 'super evil slimy greedy venture capitalists' hijacking decentralization",
    episode: "Breaking Into Crypto Feat. Mike Demarais",
    episodeNumber: 56,
    guest: "Mike Demarais",
    guestTitle: "Co-founder, Rainbow Wallet",
    date: "2021-12-02",
    youtubeId: "VD5RDcFM7xM",
    startSeconds: 1620,
    endSeconds: 1770,
    viralityScore: 8.7,
    energy: "high",
    type: "hot_take",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X", "LinkedIn"],
    tags: ["VCs", "decentralization", "governance", "DeFi"],
    sentiment: "bearish",
  },
  {
    id: "clip-009",
    title: "Your ETH Wallet Is Your New Login",
    hook: "Forget Facebook and Google login — your Ethereum wallet will be your universal Web3 identity",
    episode: "Breaking Into Crypto Feat. Mike Demarais",
    episodeNumber: 56,
    guest: "Mike Demarais",
    guestTitle: "Co-founder, Rainbow Wallet",
    date: "2021-12-02",
    youtubeId: "VD5RDcFM7xM",
    startSeconds: 3480,
    endSeconds: 3600,
    viralityScore: 8.3,
    energy: "high",
    type: "insight",
    platforms: ["LinkedIn", "YT Shorts", "X", "TikTok"],
    tags: ["identity", "Web3", "wallet", "Rainbow"],
    sentiment: "bullish",
  },

  // ═══ BRANTLY.ETH — Ep 69 ═══
  {
    id: "clip-010",
    title: "Bitcoin $100K Is Coming",
    hook: "Logan breaks down the historical chart pattern that makes $100K Bitcoin inevitable — sooner than you think",
    episode: "Brantly.eth On Digital Identity",
    episodeNumber: 69,
    date: "2022-02-04",
    youtubeId: "gUhKgGUvyJE",
    startSeconds: 200,
    endSeconds: 235,
    viralityScore: 8.8,
    energy: "high",
    type: "hot_take",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["Bitcoin", "price prediction", "chart analysis"],
    sentiment: "bullish",
  },
  {
    id: "clip-011",
    title: "BTC Over $40K — Canceling My McDonald's App",
    hook: "Bitcoin crossed $40,000 so Logan can officially take back his McDonald's application",
    episode: "Brantly.eth On Digital Identity",
    episodeNumber: 69,
    date: "2022-02-04",
    youtubeId: "gUhKgGUvyJE",
    startSeconds: 81,
    endSeconds: 100,
    viralityScore: 8.5,
    energy: "high",
    type: "funny",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["Bitcoin", "comedy", "price action"],
    sentiment: "bullish",
  },
  {
    id: "clip-012",
    title: "Free elonmusk.eth — One Condition",
    hook: "Brantly.eth offers the elonmusk.eth domain to Elon Musk for free, but there's one condition",
    episode: "Brantly.eth On Digital Identity",
    episodeNumber: 69,
    guest: "Brantly.eth",
    guestTitle: "Director, Ethereum Name Service",
    date: "2022-02-04",
    youtubeId: "gUhKgGUvyJE",
    startSeconds: 7905,
    endSeconds: 7980,
    viralityScore: 8.2,
    energy: "medium",
    type: "guest_highlight",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["ENS", "Elon Musk", "domains", "Web3"],
    sentiment: "bullish",
  },

  // ═══ AUDIUS — Ep 80 ═══
  {
    id: "clip-013",
    title: "Why Audius Chose Solana Over Ethereum",
    hook: "Audius needed sub-second finality for music streaming — Ethereum L2s couldn't deliver",
    episode: "This Music Cryptocurrency is Integrated With TikTok",
    episodeNumber: 80,
    guest: "Austin Virts",
    guestTitle: "Head of Marketing, Audius (former Solana)",
    date: "2022-03-25",
    youtubeId: "l9JxDu72ZSo",
    startSeconds: 1209,
    endSeconds: 1343,
    viralityScore: 7.9,
    energy: "medium",
    type: "guest_highlight",
    platforms: ["LinkedIn", "YT Shorts", "X"],
    tags: ["Audius", "Solana", "Ethereum", "L2", "music"],
    sentiment: "bullish",
  },
  {
    id: "clip-014",
    title: "Audius x TikTok Changes Everything",
    hook: "Artists can now use their own music directly on TikTok through Audius — a viral loop for creators",
    episode: "This Music Cryptocurrency is Integrated With TikTok",
    episodeNumber: 80,
    guest: "Austin Virts",
    guestTitle: "Head of Marketing, Audius (former Solana)",
    date: "2022-03-25",
    youtubeId: "l9JxDu72ZSo",
    startSeconds: 1470,
    endSeconds: 1530,
    viralityScore: 8.4,
    energy: "high",
    type: "breaking_news",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["Audius", "TikTok", "music", "creator economy"],
    sentiment: "bullish",
  },
  {
    id: "clip-015",
    title: "Never Research After You Invest",
    hook: "Never do your research AFTER the investment — because at that point, your research doesn't matter",
    episode: "This Music Cryptocurrency is Integrated With TikTok",
    episodeNumber: 80,
    date: "2022-03-25",
    youtubeId: "l9JxDu72ZSo",
    startSeconds: 600,
    endSeconds: 640,
    viralityScore: 8.6,
    energy: "high",
    type: "funny",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["investing", "DYOR", "comedy", "advice"],
    sentiment: "neutral",
  },

  // ═══ FLOKI TA / BTC ETF — Ep 47 ═══
  {
    id: "clip-016",
    title: "SEC Approves First Bitcoin ETF",
    hook: "The SEC just approved the first Bitcoin Futures ETF — what this means for the entire crypto market",
    episode: "Bitcoin ETF Approved! | Floki Inu Technical Analysis",
    episodeNumber: 47,
    date: "2021-10-28",
    youtubeId: "2b1G8GJgZlU",
    startSeconds: 412,
    endSeconds: 492,
    viralityScore: 8.9,
    energy: "high",
    type: "breaking_news",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X", "LinkedIn"],
    tags: ["Bitcoin", "ETF", "SEC", "regulation"],
    sentiment: "bullish",
  },
  {
    id: "clip-017",
    title: "Safemoon Is a Slow Rug Pull",
    hook: "Safemoon is a slow rug — a pyramid scheme with multiple ways for developers to drain your funds",
    episode: "Bitcoin ETF Approved! | Floki Inu Technical Analysis",
    episodeNumber: 47,
    date: "2021-10-28",
    youtubeId: "2b1G8GJgZlU",
    startSeconds: 1655,
    endSeconds: 1730,
    viralityScore: 9.0,
    energy: "high",
    type: "hot_take",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["Safemoon", "scam", "rug pull", "warning"],
    sentiment: "bearish",
  },

  // ═══ ETHDENVER — Ep 72 ═══
  {
    id: "clip-018",
    title: "Ryan's $45K ETHDenver Expense Report",
    hook: "Ryan expensed $45,000 at ETHDenver claiming it was for a 'seed phrase' and 'traveling expenses'",
    episode: "ETHDenver Recap: Vitalik Buterin, Andrew Yang, and Kimbal Musk",
    episodeNumber: 72,
    date: "2022-02-25",
    youtubeId: "0i3727vSVJw",
    startSeconds: 695,
    endSeconds: 815,
    viralityScore: 8.7,
    energy: "high",
    type: "funny",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["ETHDenver", "comedy", "expenses", "conference"],
    sentiment: "neutral",
  },
  {
    id: "clip-019",
    title: "Logan Meets Benny Blanco at an NFT Party",
    hook: "Logan recounts meeting Benny Blanco and Malia Obama at The Heart Project NFT party in LA",
    episode: "ETHDenver Recap: Vitalik Buterin, Andrew Yang, and Kimbal Musk",
    episodeNumber: 72,
    date: "2022-02-25",
    youtubeId: "0i3727vSVJw",
    startSeconds: 1448,
    endSeconds: 1510,
    viralityScore: 8.3,
    energy: "high",
    type: "guest_highlight",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["NFT", "celebrities", "events", "Heart Project"],
    sentiment: "bullish",
  },

  // ═══ B WORD CONFERENCE — Ep 19 ═══
  {
    id: "clip-020",
    title: "Elon Reveals His Crypto Portfolio",
    hook: "Elon Musk publicly reveals he owns Bitcoin, Ethereum, and Dogecoin — plus Tesla and SpaceX hold BTC",
    episode: "The B Word LIVE REACTION",
    episodeNumber: 19,
    date: "2021-07-21",
    youtubeId: "0OIJiVYJOgk",
    startSeconds: 528,
    endSeconds: 580,
    viralityScore: 9.0,
    energy: "high",
    type: "breaking_news",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["Elon Musk", "Bitcoin", "portfolio", "Tesla"],
    sentiment: "bullish",
  },
  {
    id: "clip-021",
    title: "Elon's Dogecoin Prophecy",
    hook: "Elon Musk: 'The cryptocurrency that was started as a joke ends up being the leading cryptocurrency'",
    episode: "The B Word LIVE REACTION",
    episodeNumber: 19,
    date: "2021-07-21",
    youtubeId: "0OIJiVYJOgk",
    startSeconds: 1662,
    endSeconds: 1720,
    viralityScore: 8.8,
    energy: "high",
    type: "funny",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["Elon Musk", "Dogecoin", "prediction", "meme coins"],
    sentiment: "bullish",
  },

  // ═══ SOLANA SHUTDOWN — Ep 32 ═══
  {
    id: "clip-022",
    title: "Solana's Network Just Crashed",
    hook: "Solana's entire network crashed from bot transactions — consensus failure took it all down",
    episode: "Solana Shutdown! | Phantom Wallet Interview",
    episodeNumber: 32,
    date: "2021-09-15",
    youtubeId: "4opQRV-tsiQ",
    startSeconds: 132,
    endSeconds: 264,
    viralityScore: 8.5,
    energy: "high",
    type: "breaking_news",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["Solana", "outage", "downtime", "network"],
    sentiment: "bearish",
  },
  {
    id: "clip-023",
    title: "$50 Billion in Bitcoin — One Block",
    hook: "A single entity just moved $50 BILLION in Bitcoin within one block",
    episode: "Solana Shutdown! | Phantom Wallet Interview",
    episodeNumber: 32,
    date: "2021-09-15",
    youtubeId: "4opQRV-tsiQ",
    startSeconds: 755,
    endSeconds: 828,
    viralityScore: 8.9,
    energy: "high",
    type: "breaking_news",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["Bitcoin", "whale", "on-chain", "transfer"],
    sentiment: "neutral",
  },

  // ═══ AMAZON BTC / TIER LIST — Ep 21 ═══
  {
    id: "clip-024",
    title: "The Amazon Bitcoin Prank",
    hook: "A Crypto Twitter troll fooled the Wall Street Journal into reporting Amazon was accepting Bitcoin",
    episode: "Amazon Accepting BTC?? | Cryptocurrency Tier List",
    episodeNumber: 21,
    date: "2021-07-27",
    youtubeId: "KacMysEmomU",
    startSeconds: 389,
    endSeconds: 480,
    viralityScore: 8.7,
    energy: "high",
    type: "funny",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["Amazon", "Bitcoin", "fake news", "CT"],
    sentiment: "neutral",
  },
  {
    id: "clip-025",
    title: "Bitcoin Breaks $40K — Live Reaction",
    hook: "Bitcoin surges past $40,000 and Logan loses it on camera",
    episode: "Amazon Accepting BTC?? | Cryptocurrency Tier List",
    episodeNumber: 21,
    date: "2021-07-27",
    youtubeId: "KacMysEmomU",
    startSeconds: 1900,
    endSeconds: 1960,
    viralityScore: 8.6,
    energy: "high",
    type: "breaking_news",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["Bitcoin", "price action", "live reaction", "$40K"],
    sentiment: "bullish",
  },

  // ═══ WU-TANG NFT — Ep 45 ═══
  {
    id: "clip-026",
    title: "Wu-Tang Album: From Shkreli to NFT",
    hook: "The Wu-Tang Clan album went from Martin Shkreli to government seizure to a $4M NFT — the wildest journey in music history",
    episode: "EXCLUSIVE: Here's The Broker of $4 Million PleasrDAO Wu-Tang NFT Purchase",
    episodeNumber: 45,
    date: "2021-10-22",
    youtubeId: "zGYP5GSbAX8",
    startSeconds: 350,
    endSeconds: 420,
    viralityScore: 9.0,
    energy: "high",
    type: "breaking_news",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["Wu-Tang", "NFT", "PleasrDAO", "music"],
    sentiment: "bullish",
  },
  {
    id: "clip-027",
    title: "WorldCoin Wants Your Eyeball",
    hook: "WorldCoin is scanning your iris for free crypto — are you the product?",
    episode: "EXCLUSIVE: Here's The Broker of $4 Million PleasrDAO Wu-Tang NFT Purchase",
    episodeNumber: 45,
    date: "2021-10-22",
    youtubeId: "zGYP5GSbAX8",
    startSeconds: 167,
    endSeconds: 220,
    viralityScore: 8.4,
    energy: "high",
    type: "hot_take",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["WorldCoin", "privacy", "biometrics", "identity"],
    sentiment: "bearish",
  },

  // ═══ AVA LABS — Ep 53 ═══
  {
    id: "clip-028",
    title: "ConstitutionDAO Raised $47M in a Week",
    hook: "ConstitutionDAO raised $47 million in under a week to buy the actual US Constitution",
    episode: "We Tried Buying The Constitution… | Ava Labs President Interview",
    episodeNumber: 53,
    date: "2021-11-19",
    youtubeId: "UEjs16sHQqc",
    startSeconds: 131,
    endSeconds: 200,
    viralityScore: 8.8,
    energy: "high",
    type: "breaking_news",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["ConstitutionDAO", "governance", "crowdfunding", "history"],
    sentiment: "bullish",
  },

  // ═══ GARYVEE / ANDREW YANG — Ep 74 ═══
  {
    id: "clip-029",
    title: "95% of NFTs Will Go to Zero",
    hook: "Gary Vee's prediction: 95% of NFTs will go to zero — and Pixelmon just proved him right",
    episode: "These Guys Interviewed Who?! | GaryVee, Andrew Yang",
    episodeNumber: 74,
    date: "2022-03-04",
    youtubeId: "yMafDq3cGt0",
    startSeconds: 272,
    endSeconds: 340,
    viralityScore: 8.8,
    energy: "high",
    type: "hot_take",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X", "LinkedIn"],
    tags: ["GaryVee", "NFT", "prediction", "Pixelmon"],
    sentiment: "bearish",
  },

  // ═══ POLYNETWORK / AXIE — Ep 25 ═══
  {
    id: "clip-030",
    title: "Axie Infinity Changed the Philippines",
    hook: "Play-to-earn scholarships on Axie Infinity are replacing minimum wage jobs in the Philippines",
    episode: "PolyNetwork Hack | Axie Infinity Co-Founder Interview",
    episodeNumber: 25,
    date: "2021-08-12",
    youtubeId: "q25eGWLXE4E",
    startSeconds: 1440,
    endSeconds: 1520,
    viralityScore: 8.5,
    energy: "high",
    type: "guest_highlight",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X", "LinkedIn"],
    tags: ["Axie Infinity", "play-to-earn", "Philippines", "gaming"],
    sentiment: "bullish",
  },

  // ═══ HOLOCHAIN — Ep 70 ═══
  {
    id: "clip-031",
    title: "Sequoia Drops $450M on Polygon",
    hook: "Sequoia Capital just led a $450 million round into Polygon this morning",
    episode: "Co-Founder of Holochain Arthur Brock",
    episodeNumber: 70,
    date: "2022-02-07",
    youtubeId: "CBDsguc5k0c",
    startSeconds: 725,
    endSeconds: 780,
    viralityScore: 8.3,
    energy: "high",
    type: "breaking_news",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X", "LinkedIn"],
    tags: ["Polygon", "MATIC", "Sequoia", "funding"],
    sentiment: "bullish",
  },
  {
    id: "clip-032",
    title: "ETH Might Flip Bitcoin in 2022",
    hook: "Bold prediction: Ethereum could actually surpass Bitcoin's market cap in 2022",
    episode: "Co-Founder of Holochain Arthur Brock",
    episodeNumber: 70,
    date: "2022-02-07",
    youtubeId: "CBDsguc5k0c",
    startSeconds: 260,
    endSeconds: 310,
    viralityScore: 8.1,
    energy: "medium",
    type: "hot_take",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["Ethereum", "Bitcoin", "flippening", "prediction"],
    sentiment: "bullish",
  },

  // ═══ 2022 STRATEGIES — Ep 62 ═══
  {
    id: "clip-033",
    title: "MATIC to $10 — You Heard It Here First",
    hook: "Ryan's bold 2022 call: Polygon hits $10 — three months before the crash",
    episode: "2022 Crypto Strategies Special: Moonshots, DeFi, NFTs and Airdrops",
    episodeNumber: 62,
    date: "2022-01-03",
    youtubeId: "46ySPg7qjDE",
    startSeconds: 542,
    endSeconds: 600,
    viralityScore: 8.9,
    energy: "high",
    type: "hot_take",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["Polygon", "MATIC", "prediction", "aged like milk"],
    sentiment: "bullish",
  },
  {
    id: "clip-034",
    title: "DeFi Is NOT Dead",
    hook: "TVL in Ethereum DeFi is approaching $300 billion — DeFi isn't dead, it's just getting started",
    episode: "2022 Crypto Strategies Special: Moonshots, DeFi, NFTs and Airdrops",
    episodeNumber: 62,
    date: "2022-01-03",
    youtubeId: "46ySPg7qjDE",
    startSeconds: 2060,
    endSeconds: 2145,
    viralityScore: 8.0,
    energy: "high",
    type: "insight",
    platforms: ["LinkedIn", "YT Shorts", "X", "TikTok"],
    tags: ["DeFi", "TVL", "Ethereum", "analysis"],
    sentiment: "bullish",
  },

  // ═══ UNSTOPPABLE DOMAINS — Ep 63 ═══
  {
    id: "clip-035",
    title: ".com With Superpowers",
    hook: "Unstoppable Domains CEO explains why blockchain domains are '.com with superpowers'",
    episode: "How to Profit While ETH Crashes | Unstoppable Domains CEO Interview",
    episodeNumber: 63,
    guest: "Matthew Gould",
    guestTitle: "CEO, Unstoppable Domains",
    date: "2022-01-10",
    youtubeId: "OG78Bg1EQEM",
    startSeconds: 2049,
    endSeconds: 2130,
    viralityScore: 7.8,
    energy: "high",
    type: "guest_highlight",
    platforms: ["LinkedIn", "YT Shorts", "X"],
    tags: ["domains", "Web3", "identity", "Unstoppable"],
    sentiment: "bullish",
  },

  // ═══ TOP 100 CRYPTOS — Ep 81 ═══
  {
    id: "clip-036",
    title: "Tether Could Collapse Crypto",
    hook: "Tether's reserves might include Evergrande debt — if true, it could trigger a full crypto collapse",
    episode: "Top 100 Cryptocurrencies In 60 Minutes Challenge!",
    episodeNumber: 81,
    date: "2022-03-28",
    youtubeId: "Pl_ysv0EjJI",
    startSeconds: 192,
    endSeconds: 250,
    viralityScore: 8.5,
    energy: "medium",
    type: "hot_take",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["Tether", "USDT", "Evergrande", "stablecoin"],
    sentiment: "bearish",
  },

  // ═══ CRYPTO REGULATION — Ep 23 ═══
  {
    id: "clip-037",
    title: "Good Luck Tracking My MetaMask",
    hook: "How is the government going to track my MetaMask to tax my DeFi transactions?",
    episode: "Crypto Regulation Incoming",
    episodeNumber: 23,
    date: "2021-08-06",
    youtubeId: "OMsNb-O2dmk",
    startSeconds: 400,
    endSeconds: 450,
    viralityScore: 8.2,
    energy: "high",
    type: "hot_take",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["regulation", "DeFi", "taxes", "MetaMask"],
    sentiment: "mixed",
  },
  {
    id: "clip-038",
    title: "ETH Breaks Free From Bitcoin",
    hook: "Ethereum surges past $2,900 independently of Bitcoin — the long-awaited altcoin season begins",
    episode: "Crypto Regulation Incoming",
    episodeNumber: 23,
    date: "2021-08-06",
    youtubeId: "OMsNb-O2dmk",
    startSeconds: 110,
    endSeconds: 160,
    viralityScore: 8.0,
    energy: "high",
    type: "breaking_news",
    platforms: ["TikTok", "IG Reels", "YT Shorts", "X"],
    tags: ["Ethereum", "altcoin season", "price action", "decoupling"],
    sentiment: "bullish",
  },
];
